github_integrations.github_integrations_config_entity.*:
  type: config_entity
  label: 'GitHub Integrations Configuration config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    private_key:
      type: string
      label: 'Private key'
