github_integrations.github_integrations_config.*:
  type: config_entity
  label: 'GitHub Integration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    integration_id:
      type: integer
      label: 'Integration ID'
    private_key:
      type: string
      label: 'Private key'
